# conda environment description file for rpn-to-gemlam package
# development environment
#
# Create a conda environment for development, testing and documentation of the package
# with:
#
#   $ mamba env create -f rpn-to-gemlam/envs/environment-dev.yaml
#   $ mamba activate rpn-to-gemlam
#   (rpn-to-gemlam)$ python -m pip install --editable ../tools/SalishSeaTools
#   (rpn-to-gemlam)$ python -m pip install --editable rpn-to-gemlam
#
# The environment will include all the tools used to develop,
# test, and document the rpn-to-gemlam package.
#
# See the requirements.txt file for an exhaustive list of all the
# packages installed in the environment and their versions used in
# recent development.

name: rpn-to-gemlam

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - bottleneck
  - Click
  - matplotlib
  - netCDF4
  - pip
  - python=3.13
  - python-dateutil
  - pytz
  - requests
  - retrying
  - scipy
  - xarray

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx==8.1.3
  - sphinx-rtd-theme==3.0.0

  # For coding style
  - black

  - pip:
      - angles
