# conda environment description file for docs build envioronment
# on readthedocs.org
#
# This file is a union of the environment.yaml files in the
# SalishSeaCmd, SalishSeaNowcast, SalishSeaTools, and Marlin packages.

name: rpn-to-gemlam-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - python=3.13

  # Sphinx and extensions we use
  - sphinx=7.2.6
  - sphinx-notfound-page=1.0.0
  - sphinx-rtd-theme=2.0.0

  # readthedocs build system packages
  - mock
  - pillow
  - pip:
    - commonmark
    - recommonmark
    - readthedocs-sphinx-ext
